# © 2019 Netxillon Technologies.
# ------------------------------
# Author: Gurmukh Singh
# Email: trainings@netxillon.com
# Date: 22-06-2020
# ------------------------------

# You are free to use these as long as you acknowledge it back to the source and give due credit.

# ****************************************WARNING************************
# There is no guarantee for the use of these scripts/roles and the author
# is in no way liable for any damange caused by the use of these scripts.
# ************************************************************************
---
- name: Create PID Directory/Folder
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ airflow_pidfile_folder }}"

- name: Scheduler Service
  template:
     src:   scheduler.service
     dest:  /etc/systemd/system/airflow-scheduler.service
     owner: root
     group: root
     mode:  0644
  when: inventory_hostname in groups['airflow_scheduler']

- name: Webserver Service
  template:
     src:   webserver.service
     dest:  /etc/systemd/system/airflow-webserver.service
     owner: root
     group: root
     mode:  0644
  when: inventory_hostname in groups['airflow_webserver']

- name: Worker Service
  template:
     src:   worker.service
     dest:  /etc/systemd/system/airflow-worker.service
     owner: root
     group: root
     mode:  0644
  when: inventory_hostname in groups['airflow_worker']

- name: Issue daemon-reload to pick up config changes
  systemd:
    daemon_reload: yes

- name: Ensure Scheduler Service is Started
  service:
    name:    airflow-scheduler
    state:   restarted
    enabled: yes
  when: inventory_hostname in groups['airflow_scheduler']

- name: Ensure WebServer Service is Started
  service:
    name:    airflow-webserver
    state:   restarted
    enabled: yes
  when: inventory_hostname in groups['airflow_webserver']

- name: Ensure Worker Service is Started
  service:
    name:    airflow-worker
    state:   restarted
    enabled: yes
  when: inventory_hostname in groups['airflow_worker']

