# © 2019 Netxillon Technologies.
# ------------------------------
# Author: Gurmukh Singh
# Email: trainings@netxillon.com
# Date: 22-06-2020
# ------------------------------

# You are free to use these as long as you acknowledge it back to the source and give due credit.

# ****************************************WARNING************************
# There is no guarantee for the use of these scripts/roles and the author
# is in no way liable for any damange caused by the use of these scripts.
# ************************************************************************

---
- name: install the package, force upgrade
  pip:
    name: pip
    executable: pip3
    state: latest
- pip:
    name: psycopg2
    executable: "pip{{ pip_version }}"
    state: forcereinstall
  become: True
- pip:
    name: setuptools_rust
    executable: "pip{{ pip_version }}"
    state: forcereinstall
  become: True
- pip:
    name: wheel
    executable: "pip{{ pip_version }}"
    state: forcereinstall
  become: True
- pip:
    name: mysqlclient
    executable: "pip{{ pip_version }}"
    state: forcereinstall
  become: True
- pip:
    name: cryptography
    executable: "pip{{ pip_version }}"
    state: forcereinstall
  become: True
- pip:
    name: apache-airflow
    executable: "pip{{ pip_version }}"
    state: forcereinstall
  become: True
- pip:
    name: apache-airflow[celery]
    executable: "pip{{ pip_version }}"
    state: forcereinstall
    umask: "0022"
  become: True

